fix a i18n issue in configure, replace tabs with spaces

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -20,33 +20,33 @@ strip=1
 arch=`uname -s`
 
 while [ -n "$1" ]; do
-	e="`expr "$1" : '--\(.*=.*\)'`"
-	if [ -z "$e" ]; then
-		cat<<EOF
+    e="`expr "$1" : '--\(.*=.*\)'`"
+    if [ -z "$e" ]; then
+        cat<<EOF
 Axel configure
 
 Usage: $0 [OPTIONS]
 
-Option		Description				Default
+Option        Description                 Default
 
---prefix=...	Directories to put files in		$prefix
---bindir=...						$bindir
---etcdir=...						$etcdir
---mandir=...						$mandir
---locale=...						$locale
+--prefix=...  Directories to put files in $prefix
+--bindir=...  $bindir
+--etcdir=...  $etcdir
+--mandir=...  $mandir
+--locale=...  $locale
 
---i18n=0/1	Disable/enable internationalization	$i18n
---debug=0/1	Disable/enable debugging		$debug
---strip=0/1	Disable/enable binary stripping		$strip
+--i18n=0/1  Disable/enable internationalization $i18n
+--debug=0/1 Disable/enable debugging            $debug
+--strip=0/1 Disable/enable binary stripping     $strip
 EOF
-		exit;
-	fi
-	
-	keyname=`expr "$e" : '\(.*\)=.*' | sed 's/[^a-z0-9_]/_/g'`
-	value=`expr "$e" : '.*=\(.*\)' | sed "s/'/_/g"`
-	
-	eval "$keyname='$value'"
-	shift;
+        exit;
+    fi
+
+    keyname=`expr "$e" : '\(.*\)=.*' | sed 's/[^a-z0-9_]/_/g'`
+    value=`expr "$e" : '.*=\(.*\)' | sed "s/'/_/g"`
+
+    eval "$keyname='$value'"
+    shift;
 done
 
 # Expand $prefix
@@ -56,8 +56,8 @@ sharedir=`eval echo $sharedir`
 mandir=`eval echo $mandir`
 locale=`eval echo $locale`
 if test "$etcdir" = "/usr/etc"; then
-	# FHS explicitely forbids /usr/etc
-	etcdir='/etc'
+    # FHS explicitely forbids /usr/etc
+    etcdir='/etc'
 fi
 
 cat<<EOF>Makefile.settings
@@ -86,148 +86,147 @@ cat<<EOF>config.h
 
 EOF
 
-AXEL_LFLAGS=${LFLAGS}
-
-if [ "$i18n" = "1" ]; then
-	if type msgfmt > /dev/null 2> /dev/null; then :;else
-		echo 'WARNING: Internationalization disabled, you don'\''t have the necessary files'
-		echo '         installed.'
-		echo ''
-		i18n=0;
-	fi;
-	
-	echo "all: i18n-mofiles" >> Makefile.settings
-	echo "install: install-i18n" >> Makefile.settings
-	echo "uninstall: uninstall-i18n" >> Makefile.settings
-fi
-
-AXEL_CFLAGS="-D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -Os ${CFLAGS}"
+AXEL_CFLAGS="-D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 ${CFLAGS}"
 if [ "$debug" = "1" ]; then
-	AXEL_CFLAGS="${AXEL_CFLAGS} -g"
-	echo 'DEBUG=1' >> Makefile.settings
-	echo '#define DEBUG' >> config.h;
+    AXEL_CFLAGS="${AXEL_CFLAGS} -g"
+    echo 'DEBUG=1' >> Makefile.settings
+    echo '#define DEBUG' >> config.h;
+else
+    AXEL_CFLAGS="${AXEL_CFLAGS} -Os"
 fi
 
+if type msgfmt > /dev/null 2> /dev/null; then :;else
+    echo 'WARNING: Internationalization disabled, you don'\''t have the necessary files'
+    echo '         installed.'
+    echo ''
+    i18n=0;
+fi
+
+AXEL_LFLAGS=${LFLAGS}
 if [ "$i18n" = "1" ]; then
-	echo 'I18N=1' >> Makefile.settings
-	echo '#define I18N' >> config.h
-	if [ -f /usr/local/include/libintl.h ]; then
-		AXEL_CFLAGS="${AXEL_CFLAGS} -I/usr/local/include"
-		AXEL_LFLAGS="${AXEL_LFLAGS} -L/usr/local/lib"
-	elif [ -f /opt/csw/include/libintl.h ]; then
-		AXEL_CFLAGS="${AXEL_CFLAGS} -I/opt/csw/include"
-		AXEL_LFLAGS="${AXEL_LFLAGS} -L/opt/csw/lib"
-	elif [ -f "${prefix}/include/libintl.h" ]; then
-		AXEL_CFLAGS="${AXEL_CFLAGS} -I${prefix}/include"
-		AXEL_LFLAGS="${AXEL_LFLAGS} -L${prefix}/lib"
-	fi
+    echo "all: i18n-mofiles" >> Makefile.settings
+    echo "install: install-i18n" >> Makefile.settings
+    echo "uninstall: uninstall-i18n" >> Makefile.settings
+
+    echo 'I18N=1' >> Makefile.settings
+    echo '#define I18N' >> config.h
+    if [ -f /usr/local/include/libintl.h ]; then
+        AXEL_CFLAGS="${AXEL_CFLAGS} -I/usr/local/include"
+        AXEL_LFLAGS="${AXEL_LFLAGS} -L/usr/local/lib"
+    elif [ -f /opt/csw/include/libintl.h ]; then
+        AXEL_CFLAGS="${AXEL_CFLAGS} -I/opt/csw/include"
+        AXEL_LFLAGS="${AXEL_LFLAGS} -L/opt/csw/lib"
+    elif [ -f "${prefix}/include/libintl.h" ]; then
+        AXEL_CFLAGS="${AXEL_CFLAGS} -I${prefix}/include"
+        AXEL_LFLAGS="${AXEL_LFLAGS} -L${prefix}/lib"
+    fi
 fi
 
 if [ "${CC}" != "" ]; then
-	echo "CC=${CC}" >> Makefile.settings;
+    echo "CC=${CC}" >> Makefile.settings;
 elif type gcc > /dev/null 2> /dev/null; then
-	echo "CC=gcc" >> Makefile.settings;
-	AXEL_CFLAGS="${AXEL_CFLAGS} -Wall"
+    echo "CC=gcc" >> Makefile.settings;
+    AXEL_CFLAGS="${AXEL_CFLAGS} -Wall"
 elif type cc > /dev/null 2> /dev/null; then
-	echo "CC=cc" >> Makefile.settings;
+    echo "CC=cc" >> Makefile.settings;
 else
-	echo 'Cannot find a C compiler, aborting.'
-	exit 1;
+    echo 'Cannot find a C compiler, aborting.'
+    exit 1;
 fi
 
 if [ "$strip" = 0 ]; then
-	echo "STRIP=\# skip strip" >> Makefile.settings;
+    echo "STRIP=\# skip strip" >> Makefile.settings;
 else
-	if [ "$debug" = 1 ]; then
-		echo 'Stripping binaries does not make sense when debugging. Stripping disabled.'
-		echo
-		echo 'STRIP=\# skip strip' >> Makefile.settings
-		strip=0;
-	elif type strip > /dev/null 2> /dev/null; then
-		echo "STRIP=strip" >> Makefile.settings;
-	elif [ -x /usr/ccs/bin/strip ]; then
-		echo "STRIP=/usr/ccs/bin/strip" >> Makefile.settings;
-	else
-		echo 'No strip utility found, cannot remove unnecessary parts from executable.'
-		echo ''
-		echo 'STRIP=\# skip strip' >> Makefile.settings
-		strip=0;
-	fi;
+    if [ "$debug" = 1 ]; then
+        echo 'Stripping binaries does not make sense when debugging. Stripping disabled.'
+        echo
+        echo 'STRIP=\# skip strip' >> Makefile.settings
+        strip=0;
+    elif type strip > /dev/null 2> /dev/null; then
+        echo "STRIP=strip" >> Makefile.settings;
+    elif [ -x /usr/ccs/bin/strip ]; then
+        echo "STRIP=/usr/ccs/bin/strip" >> Makefile.settings;
+    else
+        echo 'No strip utility found, cannot remove unnecessary parts from executable.'
+        echo ''
+        echo 'STRIP=\# skip strip' >> Makefile.settings
+        strip=0;
+    fi;
 fi
 
 case "$arch" in
 FreeBSD )
-	echo '#define NOGETOPTLONG' >> config.h
-	AXEL_LFLAGS="${AXEL_LFLAGS} -pthread"
-	if [ "$i18n" = "1" ]; then
-		AXEL_LFLAGS="${AXEL_LFLAGS} -lintl"
-	fi
+    echo '#define NOGETOPTLONG' >> config.h
+    AXEL_LFLAGS="${AXEL_LFLAGS} -pthread"
+    if [ "$i18n" = "1" ]; then
+        AXEL_LFLAGS="${AXEL_LFLAGS} -lintl"
+    fi
 ;;
 OpenBSD )
-	echo '#define NOGETOPTLONG' >> config.h
-	AXEL_LFLAGS="${AXEL_LFLAGS} -pthread"
-	if [ "$i18n" = "1" ]; then
-		AXEL_LFLAGS="${AXEL_LFLAGS} -lintl"
-	fi
+    echo '#define NOGETOPTLONG' >> config.h
+    AXEL_LFLAGS="${AXEL_LFLAGS} -pthread"
+    if [ "$i18n" = "1" ]; then
+        AXEL_LFLAGS="${AXEL_LFLAGS} -lintl"
+    fi
 ;;
 NetBSD )
-	echo 'WARNING: NetBSD not tested! Using OpenBSD settings.'
-	echo '#define NOGETOPTLONG' >> config.h
-	AXEL_LFLAGS="${AXEL_LFLAGS} -pthread"
-	if [ "$i18n" = "1" ]; then
-		AXEL_LFLAGS="${AXEL_LFLAGS} -lintl"
-	fi
+    echo 'WARNING: NetBSD not tested! Using OpenBSD settings.'
+    echo '#define NOGETOPTLONG' >> config.h
+    AXEL_LFLAGS="${AXEL_LFLAGS} -pthread"
+    if [ "$i18n" = "1" ]; then
+        AXEL_LFLAGS="${AXEL_LFLAGS} -lintl"
+    fi
 ;;
 Darwin )
-	echo '#define NOGETOPTLONG' >> config.h
-	AXEL_LFLAGS="${AXEL_LFLAGS} -pthread"
-	if [ "$i18n" = "1" ]; then
-		AXEL_LFLAGS="${AXEL_LFLAGS} -lintl"
-	fi
-	echo '#define DARWIN' >> config.h
+    echo '#define NOGETOPTLONG' >> config.h
+    AXEL_LFLAGS="${AXEL_LFLAGS} -pthread"
+    if [ "$i18n" = "1" ]; then
+        AXEL_LFLAGS="${AXEL_LFLAGS} -lintl"
+    fi
+    echo '#define DARWIN' >> config.h
 ;;
 Linux | GNU/kFreeBSD)
-	AXEL_LFLAGS="${AXEL_LFLAGS} -pthread"
+    AXEL_LFLAGS="${AXEL_LFLAGS} -pthread"
 ;;
 SunOS )
-	echo '#define NOGETOPTLONG' >> config.h
-	echo '#define BSD_COMP' >> config.h
-	AXEL_LFLAGS="${AXEL_LFLAGS} -pthread -lsocket -lnsl"
-	if [ "$i18n" = "1" ]; then
-		AXEL_LFLAGS="${AXEL_LFLAGS} -lintl"
-	fi
+    echo '#define NOGETOPTLONG' >> config.h
+    echo '#define BSD_COMP' >> config.h
+    AXEL_LFLAGS="${AXEL_LFLAGS} -pthread -lsocket -lnsl"
+    if [ "$i18n" = "1" ]; then
+        AXEL_LFLAGS="${AXEL_LFLAGS} -lintl"
+    fi
 ;;
 HP-UX )
-	echo '#define NOGETOPTLONG' >> config.h
-	if [ "$i18n" = "1" ]; then
-		if [ -d /usr/local/lib/hpux32 ]; then
-			AXEL_LFLAGS="${AXEL_LFLAGS} -L/usr/local/lib/hpux32"
-		fi
-		AXEL_LFLAGS="${AXEL_LFLAGS} -lintl"
-	fi
-	AXEL_LFLAGS="${AXEL_LFLAGS} -lpthread"
+    echo '#define NOGETOPTLONG' >> config.h
+    if [ "$i18n" = "1" ]; then
+        if [ -d /usr/local/lib/hpux32 ]; then
+            AXEL_LFLAGS="${AXEL_LFLAGS} -L/usr/local/lib/hpux32"
+        fi
+        AXEL_LFLAGS="${AXEL_LFLAGS} -lintl"
+    fi
+    AXEL_LFLAGS="${AXEL_LFLAGS} -lpthread"
 ;;
 CYGWIN_* )
-	AXEL_LFLAGS="${AXEL_LFLAGS} -pthread"
-	if [ "$i18n" = "1" ]; then
-		AXEL_LFLAGS="${AXEL_LFLAGS} -lintl"
-	fi
-	echo 'OUTFILE=axel.exe' >> Makefile.settings
+    AXEL_LFLAGS="${AXEL_LFLAGS} -pthread"
+    if [ "$i18n" = "1" ]; then
+        AXEL_LFLAGS="${AXEL_LFLAGS} -lintl"
+    fi
+    echo 'OUTFILE=axel.exe' >> Makefile.settings
 ;;
 * )
-	AXEL_LFLAGS="${AXEL_LFLAGS} -pthread"
-	echo '#define NOGETOPTLONG' >> config.h
-	if [ "$i18n" = "1" ]; then
-		AXEL_LFLAGS="${AXEL_LFLAGS} -lintl";
-	fi
-	echo 'WARNING: This architecture is unknown!'
-	echo ''
-	echo 'That does not mean Axel will not work, it just means Axel is not tested on it.'
-	echo 'It'\''d be a great help if you could send me more information'
-	echo 'about your platform so that it can be addedto the build tools.'
-	echo 'You can try to build the program now, if you wish, this default setup might'
-	echo 'just work.'
-	echo ''
+    AXEL_LFLAGS="${AXEL_LFLAGS} -pthread"
+    echo '#define NOGETOPTLONG' >> config.h
+    if [ "$i18n" = "1" ]; then
+        AXEL_LFLAGS="${AXEL_LFLAGS} -lintl";
+    fi
+    echo 'WARNING: This architecture is unknown!'
+    echo ''
+    echo 'That does not mean Axel will not work, it just means Axel is not tested on it.'
+    echo 'It'\''d be a great help if you could send me more information'
+    echo 'about your platform so that it can be addedto the build tools.'
+    echo 'You can try to build the program now, if you wish, this default setup might'
+    echo 'just work.'
+    echo ''
 ;;
 esac
 
@@ -236,17 +235,17 @@ echo "LFLAGS=${AXEL_LFLAGS}" >> Makefile.settings
 
 echo 'Configuration done:'
 if [ "$i18n" = "1" ]; then
-	echo '  Internationalization enabled.';
+    echo '  Internationalization enabled.';
 else
-	echo '  Internationalization disabled.';
+    echo '  Internationalization disabled.';
 fi
 if [ "$debug" = "1" ]; then
-	echo '  Debugging enabled.';
+    echo '  Debugging enabled.';
 else
-	echo '  Debugging disabled.';
+    echo '  Debugging disabled.';
 fi
 if [ "$strip" = "1" ]; then
-	echo '  Binary stripping enabled.';
+    echo '  Binary stripping enabled.';
 else
-	echo '  Binary stripping disabled.';
+    echo '  Binary stripping disabled.';
 fi
